---
resource_types:
  - name: pull-request
    type: registry-image
    source:
      repository: docker.io/teliaoss/github-pr-resource
resources:
  - name: pull-request
    type: pull-request
    icon: source-branch
    webhook_token: ((webhook-token))
    source:
      repository: realliance/senior-game
      access_token: ((github-access-token))
      disable_ci_skip: true
      disable_forks: true
  - name: oci-build-task
    type: registry-image
    icon: docker
    source:
      repository: docker.io/vito/oci-build-task
  - name: senior-game-main
    type: git
    icon: git
    webhook_token: ((webhook-token))
    source:
      uri: https://github.com/realliance/senior-game
      branch: main
  - name: senior-game-tagged-release
    type: git
    icon: git
    webhook_token: ((webhook-token))
    source:
      uri: https://github.com/realliance/senior-game
      tag_filter: '*'
      branch: main
  - name: quay
    type: registry-image
    icon: docker
    source:
      repository: quay.io/realliance/senior-game
      username: ((quay-ci-account.username))
      password: ((quay-ci-account.token))
  - name: rust-nightly
    type: registry-image
    icon: docker
    source:
      repository: docker.io/rustlang/rust
      tag: nightly-buster
  - name: busybox
    type: registry-image
    icon: docker
    source:
      repository: busybox
  - name: python
    type: registry-image
    icon: docker
    source:
      repository: docker.io/python
jobs:
  - name: set-pipeline
    plan:
      - get: senior-game-main
        trigger: true
      - set_pipeline: self
        file: senior-game-main/ci/ci.yaml
  - name: validate-pr
    plan:
      - get: pull-request
        trigger: true
        version: check_every
      - put: pull-request
        params:
          path: pull-request
          status: pending
      - get: rust-nightly
      - get: python
      - in_parallel:
          - task: linting
            image: rust-nightly
            config:
              platform: linux
              params:
                CARGO_HOME: ./cargo
              caches:
                - path: target
                - path: cargo
                - path: apt
              inputs:
                - name: pull-request
                  path: .
              run:
                path: /bin/sh
                args:
                  - -exc
                  - |
                    apt-get update -o Dir::Cache=$PWD/apt > /dev/null
                    apt-get install -yqq --no-install-recommends \
                    -o Dir::Cache=$PWD/apt \
                    clang lld libasound2-dev libudev-dev > /dev/null
                    cargo clippy
          - task: rustfmt
            image: rust-nightly
            config:
              platform: linux
              inputs:
                - name: pull-request
                  path: .
              run:
                path: /bin/sh
                args:
                  - -exc
                  - |
                    cargo fmt -- --check
          - task: unit-test
            image: rust-nightly
            config:
              platform: linux
              params:
                CARGO_HOME: ./cargo
              caches:
                - path: target
                - path: cargo
                - path: apt
              inputs:
                - name: pull-request
                  path: .
              run:
                path: /bin/sh
                args:
                  - -exc
                  - |
                    apt-get update -o Dir::Cache=$PWD/apt > /dev/null
                    apt-get install -yqq --no-install-recommends \
                    -o Dir::Cache=$PWD/apt \
                    clang lld libasound2-dev libudev-dev > /dev/null
                    cargo test
          - task: yamllint
            image: python
            config:
              platform: linux
              inputs:
                - name: pull-request
                  path: .
              caches:
                - path: cache
              run:
                path: /bin/sh
                args:
                  - -exc
                  - |
                    pip install --cache-dir ./cache yamllint > /dev/null
                    yamllint .
          - task: pre-commit
            image: python
            params:
              SKIP: no-commit-to-branch,validate-pipeline,renovate-config,lint-apidocs
            config:
              platform: linux
              inputs:
                - name: pull-request
                  path: .
              caches:
                - path: cache
              run:
                path: /bin/sh
                args:
                  - -exc
                  - |
                    pip install --cache-dir ./cache pre-commit > /dev/null
                    pre-commit run --all-files
        on_failure:
          put: pull-request
          params:
            path: pull-request
            status: failure
      - put: pull-request
        params:
          path: pull-request
          status: success
  - name: tagged-release
    plan:
      - get: senior-game-tagged-release
        trigger: true
      - get: oci-build-task
      - get: busybox
      - load_var: tag
        file: .git/ref
      - task: build
        image: oci-build-task
        config:
          platform: linux
          inputs:
            - name: senior-game-tagged-release
              path: .
          ouputs:
            - name: image
          caches:
            - path: caches
          run:
            path: build
      - put: quay
        params:
          image: image/image.tar
          version: ((.:tag))
